language: rust
sudo: false

matrix:
  include:

  # Builds with wasm-pack.
  - rust: beta
    env: RUST_BACKTRACE=1
    before_script:
      - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
      - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
      - cargo install-update -a
      - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    script:
      - cargo generate --git . --name testing
      - cd testing && wasm-pack build

  # Builds on nightly.
  - rust: nightly
    env: RUST_BACKTRACE=1
    before_script:
      - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
      - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
      - cargo install-update -a
      - rustup target add wasm32-unknown-unknown
    script:
      - cargo generate --git . --name testing
      - cd testing && cargo check
      - cd testing && cargo check --target wasm32-unknown-unknown
      - cd testing && cargo check                                 --no-default-features
      - cd testing && cargo check --target wasm32-unknown-unknown --no-default-features
      - cd testing && cargo check                                 --no-default-features --features console_error_panic_hook
      - cd testing && cargo check --target wasm32-unknown-unknown --no-default-features --features console_error_panic_hook
      - cd testing && cargo check                                 --no-default-features --features "console_error_panic_hook wee_alloc"
      - cd testing && cargo check --target wasm32-unknown-unknown --no-default-features --features "console_error_panic_hook wee_alloc"

  # Builds on beta.
  - rust: beta
    env: RUST_BACKTRACE=1
    before_script:
      - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
      - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
      - cargo install-update -a
      - rustup target add wasm32-unknown-unknown
    script:
      - cargo generate --git . --name testing
      - cd testing && cargo check
      - cd testing && cargo check --target wasm32-unknown-unknown
      - cd testing && cargo check                                 --no-default-features
      - cd testing && cargo check --target wasm32-unknown-unknown --no-default-features
      - cd testing && cargo check                                 --no-default-features --features console_error_panic_hook
      - cd testing && cargo check --target wasm32-unknown-unknown --no-default-features --features console_error_panic_hook
      # Note: no enabling the `wee_alloc` feature here because it requires
      # nightly for now.
